[package]
name = "domo_pitchfork"
version = "1.4.0"
authors = ["Tom Wilson <tom.wilson.pdx@outlook.com>"]
license = "MIT"
readme = "README.md"
description = "Domo API Sdk"
repository = "https://github.com/quantumZebraPDX/domo-pitchfork"
keywords=["Domo"]
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["default-tls"]

default-tls = ["reqwest/default-tls"]
default-tls-vendored = ["reqwest/default-tls-vendored"]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.3"
reqwest = { version = "0.9", default-features = false }
csv = "1.1"
log = "0.4"

[dependencies.chrono]
features = ["serde", "rustc-serialize"]
version = "0.4"

[dev-dependencies]
doc-comment = "0.3"
