[package]
name = "domo-pitchfork-derive"
version = "0.1.0"
authors = ["Ryan T. Wilson <ryan@signalv.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1", features = ["full"] }
quote = "1"
domo_pitchfork = { path = "../domo-pitchfork" }